package weekly.bw138.A;

/**
 * 3270. Find the Key of the Numbers
 *
 * https://leetcode.cn/contest/biweekly-contest-138/problems/find-the-key-of-the-numbers/
 *
 * You are given three positive integers num1, num2, and num3.
 *
 * The key of num1, num2, and num3 is defined as a four-digit number such that:
 *
 * Initially, if any number has less than four digits, it is padded with leading zeros.
 *
 * The ith digit (1 <= i <= 4) of the key is generated by taking the smallest digit
 * among the ith digits of num1, num2, and num3.
 *
 * Return the key of the three numbers without leading zeros (if any).
 */

public class Solution {

    public int generateKey(int num1, int num2, int num3) {
        char[] ans = new char[]{'9', '9', '9', '9'};
        min(ans, String.valueOf(num1 + 10000).toCharArray());
        min(ans, String.valueOf(num2 + 10000).toCharArray());
        min(ans, String.valueOf(num3 + 10000).toCharArray());

        return Integer.parseInt(new String(ans));
    }

    private void min(char[] ans, char[] num) {
        for (int i = 0; i < ans.length; i++) {
            ans[i] = (char) Math.min(ans[i], num[i + 1]);
        }
    }

    public static void main(String[] args) {
    }

}
