package problem.p389findthedifference;

/**
 * 389. Find the Difference
 *
 * https://leetcode-cn.com/problems/find-the-difference/
 *
 * You are given two strings s and t.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Return the letter that was added to t.
 */

public class Solution {

    public char findTheDifference(String s, String t) {
        int[] chars = new int[26];
        int sz1 = s.length(), sz2 = t.length();
        for (int i = 0; i < sz1; i++) {
            chars[s.charAt(i) - 'a']++;
        }
        for (int i = 0; i < sz2;i++) {
            if (chars[t.charAt(i) - 'a'] == 0) {
                return t.charAt(i);
            }
            chars[t.charAt(i) - 'a']--;
        }
        return '0'; // unreached
    }

    public static void main(String[] args) {
        assert new Solution().findTheDifference("abcd", "abcde") == 'e';
        assert new Solution().findTheDifference("", "y") == 'y';
        assert new Solution().findTheDifference("a", "aa") == 'a';
        assert new Solution().findTheDifference("ae", "aea") == 'a';
    }

}
